baseURL = 'http://davidgampamole/github.io'
title = 'David Gampamole'
theme = 'lynx-stable'
languageCode = "en"
defaultContentLanguage = "en"

# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "David Gampamole"
  headline = "Hai senang berkenalan denganmu."
  image = "me.jpg"
  links = [
    { instagram = "https://www.instagram.com/david.gampamole" },
    { instagram = { href = "https://www.instagram.com/_davaga", text = "_davaga" } },
    { facebook = "https://facebook.com/davidgampamole" },
    { twitter = "https://twitter.com/_davidgampamole" },
    { github = "https://github.com/" },
    { youtube = "https://www.youtube.com/channel/UC3c8h1vRnagVHPymajUaHpg?sub_confirmation=1" },
    { twitch = "https://www.twitch.tv/jejago_" },
    { block = { text = "Website" } },
    { flickr = "https://www.flickr.com/photos/davidgampamole"},
    { tumblr = "https://davidgampamole.tumblr.com" },
    { link = { href = "https://davidgampamole.blogspot.com", text = "Blog" } },
    { lastfm = "https://www.last.fm/user/extrain_ge" },
    { letterboxd = "https://letterboxd.com/_davaga" },
    { trakt = "https://trakt.tv/users/davaga" },
    { goodreads = "https://www.goodreads.com/davidgampamole" },
    { steam = "https://steamcommunity/id/davidgampamole" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
